'use strict';
const KEY='bet_tracker_v1',main=document.getElementById('main'),labels={pending:'In corso',won:'Vinta',lost:'Persa',void:'Annullata',cashout:'Cash out'};
const emptyDB=()=>({version:2,accounts:[{id:'main',name:'Saldo',initial:0}],bets:[],transactions:[],settings:{monthlyLimit:0,favorites:[],recent:[],lastExport:null}});
let db=emptyDB(),storageError='',tab='home',filter={period:'month',day:U.local().slice(0,10),from:'',to:'',basis:'placed',status:'all',query:'',calendar:false,month:U.local().slice(0,7)},chartPoints=[];
function validDB(d){const id=x=>typeof x==='string'&&/^[\w-]+$/.test(x),nonneg=x=>U.finite(x)&&x>=0; if(!d||!Array.isArray(d.accounts)||!Array.isArray(d.bets)||!Array.isArray(d.transactions))return false;const accounts=new Set(d.accounts.map(a=>a?.id));return accounts.size===d.accounts.length&&d.accounts.every(a=>id(a.id)&&typeof a.name==='string'&&nonneg(a.initial))&&new Set(d.bets.map(b=>b?.id)).size===d.bets.length&&d.bets.every(b=>id(b.id)&&accounts.has(b.account)&&nonneg(b.stake)&&b.stake>0&&U.validDate(b.date)&&Object.hasOwn(labels,b.status)&&Array.isArray(b.legs)&&b.legs.length>0&&b.legs.every(l=>typeof l.event==='string'&&typeof l.pick==='string'&&U.finite(l.odds)&&l.odds>=1&&(!l.status||['pending','won','lost','void'].includes(l.status)))&&Number.isFinite(b.legs.reduce((n,l)=>n*l.odds,b.stake))&&(!b.settledAt||U.validDate(b.settledAt))&&(b.actualPayout==null||nonneg(b.actualPayout))&&(b.status!=='cashout'||nonneg(b.cashout)))&&new Set(d.transactions.map(t=>t?.id)).size===d.transactions.length&&d.transactions.every(t=>id(t.id)&&accounts.has(t.account)&&U.finite(t.amount)&&U.validDate(t.date))&&(!d.settings||(typeof d.settings==='object'&&nonneg(d.settings.monthlyLimit??0)&&(!d.settings.favorites||Array.isArray(d.settings.favorites)&&d.settings.favorites.every(v=>typeof v==='string'))&&(!d.settings.recent||Array.isArray(d.settings.recent)&&d.settings.recent.every(v=>typeof v==='string'))));}
function normalize(d){const a=d.accounts[0]||{id:'main'};return {version:2,accounts:[{id:a.id,name:'Saldo',initial:U.round(d.accounts.reduce((n,a)=>n+a.initial,0))}],bets:d.bets.map(b=>({...b,account:a.id,legs:b.legs.map(l=>({event:l.event,pick:l.pick,odds:l.odds,status:l.status||'pending'}))})),transactions:d.transactions.map(t=>({...t,account:a.id})),settings:{...emptyDB().settings,...d.settings}};}
try{const raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(!validDB(data))throw Error('Dati non validi');db=normalize(data)}}catch(e){storageError='Dati non leggibili: usa Altro → Importa backup. I dati originali non saranno sovrascritti.'}
function commit(next,{restore=false}={}){if(storageError&&!restore){U.toast('Ripristina un backup valido dalla sezione Altro.');return false}try{const serialized=JSON.stringify(next);if(!validDB(next))throw Error('Dati non validi');localStorage.setItem(KEY,serialized);db=next;storageError='';render();return true}catch(e){U.toast('Salvataggio non riuscito. Esporta un backup; le modifiche non sono state applicate.');return false}}
function mutate(fn){const n=U.clone(db);fn(n);return commit(n)}
function odds(b){return b.legs.reduce((n,l)=>n*(l.status==='void'?1:l.odds),1)}
function payout(b){if(b.status==='pending'||b.status==='lost')return 0;if(b.actualPayout!=null)return b.actualPayout;return b.status==='won'?U.round(b.stake*odds(b)):b.status==='void'?b.stake:b.cashout||0}
function profit(b){return b.status==='pending'?0:U.round(payout(b)-b.stake)}
function balance(){return U.round(db.accounts[0].initial+db.transactions.reduce((n,t)=>n+t.amount,0)+db.bets.reduce((n,b)=>n-b.stake+payout(b),0))}
function dateFor(b){return filter.basis==='settled'?(b.status==='pending'?null:b.settledAt):b.date}
function selectedBets(ignorePeriod=false){const bounds=U.bounds(filter.period,filter.day,filter.from,filter.to);return db.bets.filter(b=>(ignorePeriod||U.inRange(dateFor(b),bounds))&&(filter.basis!=='settled'||b.status!=='pending'&&b.settledAt)&&(tab!=='bets'||filter.status==='all'||b.status===filter.status)&&(!filter.query||b.legs.some(l=>(l.event+' '+l.pick).toLocaleLowerCase().includes(filter.query.toLocaleLowerCase())))).sort((a,b)=>new Date(dateFor(b))-new Date(dateFor(a)))}
function card(b){const pending=b.status==='pending',kind=b.legs.length>1?'Multipla · '+b.legs.length+' eventi':'Singola';return `<div class="card bet-card ${pending?'is-pending':''}"><div class="row bet-card-head"><div class="bet-card-title"><b>${kind}</b>${pending?`<span class="badge pending">${labels[b.status]}</span>`:''}</div>${pending?`<div class="quick-outcomes" aria-label="Esito rapido"><button class="good" type="button" data-quick="won" data-id="${b.id}" aria-label="Segna scommessa come vinta" title="Vinta">✓</button><button class="danger" type="button" data-quick="lost" data-id="${b.id}" aria-label="Segna scommessa come persa" title="Persa">×</button></div>`:`<span class="badge ${b.status}">${labels[b.status]}</span>`}</div><p>${b.legs.map(l=>`${U.esc(l.event)} · ${U.esc(l.pick)} <small>(${l.odds.toFixed(2)})${l.status!=='pending'?' · '+labels[l.status]:''}</small>`).join('<br>')}</p><small>Giocata ${U.date(b.date)}${b.settledAt?'<br>Esito '+U.date(b.settledAt):''}</small><div class="row wrap section"><span>Puntata <b>${U.money(b.stake)}</b></span><span>Quota <b>${odds(b).toFixed(2)}</b></span></div><div class="row"><small>${pending?'Incasso potenziale':'Incasso effettivo'}</small><b>${U.money(pending?b.stake*odds(b):payout(b))}</b></div>${!pending?`<div class="row"><small>Profitto netto</small><b class="${profit(b)<0?'negative':'positive'}">${U.money(profit(b))}</b></div>`:''}<div class="actions bet-card-actions"><button class="blue bet-outcomes-button" data-settle="${b.id}">Altri esiti</button><button data-edit="${b.id}">Modifica</button><button class="danger" data-delete="${b.id}">Elimina</button></div></div>`}
function winRate(bets){const won=bets.filter(b=>b.status==='won').length,played=bets.filter(b=>['won','lost'].includes(b.status)).length;return {won,played,percentage:played?100*won/played:null}}
function kpis(bets,{interactive=false,context=''}={}){const closed=bets.filter(b=>b.status!=='pending'),net=closed.reduce((n,b)=>n+profit(b),0),rate=winRate(bets),items=[['stake','Totale puntato',U.money(bets.reduce((n,b)=>n+b.stake,0)),'Tutte le giocate'],['profit','Profitto netto',U.money(net),'Scommesse concluse'],['payout','Incassi liquidati',U.money(closed.reduce((n,b)=>n+payout(b),0)),'Esiti registrati'],['winrate','Percentuale vinte',rate.percentage===null?'—':rate.percentage.toLocaleString('it-IT',{maximumFractionDigits:1})+'%',rate.played?rate.won+' vinte su '+rate.played+' concluse':'Nessuna vinta o persa']];return `<div class="grid kpi-grid ${context}">${items.map(([key,title,value,detail])=>interactive?`<button type="button" class="card kpi-card kpi-action" data-kpi="${key}" aria-label="Apri dettaglio ${title}"><small class="kpi-title">${title}</small><div class="value">${value}</div><small class="kpi-detail">${detail}</small><span class="kpi-open" aria-hidden="true">›</span></button>`:`<div class="card kpi-card"><small class="kpi-title">${title}${key==='winrate'?' <button class="help" data-roi aria-label="Come si calcola la percentuale vinte">ⓘ</button>':''}</small><div class="value">${value}</div><small class="kpi-detail">${detail}</small></div>`).join('')}</div>`}
function kpiLabel(b){return b.legs.length>1?`Multipla · ${b.legs.length} eventi`:(b.legs[0]?.event||'Scommessa')}
function kpiPanel(kind,bets){const closed=bets.filter(b=>b.status!=='pending'),rate=winRate(bets),configs={stake:{title:'Totale puntato',summary:`${bets.length} scommesse · ${U.money(bets.reduce((n,b)=>n+b.stake,0))}`,rows:bets,date:b=>b.date,value:b=>U.money(b.stake),tone:()=>''},profit:{title:'Profitto netto',summary:`${closed.length} concluse · ${U.money(closed.reduce((n,b)=>n+profit(b),0))}`,rows:closed,date:b=>b.settledAt||b.date,value:b=>U.money(profit(b)),tone:b=>profit(b)<0?'negative':'positive'},payout:{title:'Incassi liquidati',summary:`${closed.length} esiti · ${U.money(closed.reduce((n,b)=>n+payout(b),0))}`,rows:closed,date:b=>b.settledAt||b.date,value:b=>U.money(payout(b)),tone:()=>''},winrate:{title:'Percentuale vinte',summary:rate.played?`${rate.won} vinte su ${rate.played} concluse · ${rate.percentage.toLocaleString('it-IT',{maximumFractionDigits:1})}%`:'Nessuna scommessa vinta o persa',rows:bets.filter(b=>['won','lost'].includes(b.status)),date:b=>b.settledAt||b.date,value:b=>labels[b.status],tone:b=>b.status==='won'?'positive':'negative'}};const c=configs[kind]||configs.stake,rows=c.rows.slice().sort((a,b)=>new Date(c.date(b))-new Date(c.date(a))).slice(0,8),more=Math.max(0,c.rows.length-rows.length);return U.modal(U.head(c.title)+`<p class="kpi-panel-summary">${c.summary}</p><div class="kpi-panel-list">${rows.length?rows.map(b=>`<div class="kpi-panel-row"><div><b>${U.esc(kpiLabel(b))}</b><small>${U.date(c.date(b))} · ${labels[b.status]}</small></div><strong class="${c.tone(b)}">${c.value(b)}</strong></div>`).join(''):'<div class="empty kpi-panel-empty">Nessun dato disponibile.</div>'}</div>${more?`<p class="muted kpi-panel-more">Mostrate le 8 più recenti su ${c.rows.length}.</p>`:''}`)}
function filters(){return `<div class="card"><div class="filters"><select id="period" aria-label="Periodo">${[['month','Questo mese'],['week','Questa settimana'],['year','Quest’anno'],['all','Tutto lo storico'],['day','Giorno / calendario'],['custom','Intervallo personalizzato']].map(([v,l])=>`<option value="${v}" ${filter.period===v?'selected':''}>${l}</option>`).join('')}</select><select id="basis" aria-label="Data di riferimento"><option value="placed" ${filter.basis==='placed'?'selected':''}>Giocate nel periodo</option><option value="settled" ${filter.basis==='settled'?'selected':''}>Liquidate nel periodo</option></select></div>${filter.period==='day'?`<input id="day" type="date" aria-label="Giorno" value="${filter.day}">${U.calendar(filter.month,filter.day,key=>{const rows=selectedBets(true).filter(b=>dateFor(b)&&U.local(new Date(dateFor(b))).slice(0,10)===key);return rows.length?`${rows.length} · ${U.round(rows.reduce((n,b)=>n+profit(b),0))}€`:''})}`:''}${filter.period==='custom'?`<div class="grid"><div><label>Dal</label><input id="from" type="date" value="${filter.from}"></div><div><label>Al</label><input id="to" type="date" value="${filter.to}"></div></div>`:''}${tab==='bets'?`<label>Esito</label><select id="status"><option value="all">Tutti gli esiti</option>${Object.entries(labels).map(([v,l])=>`<option value="${v}" ${filter.status===v?'selected':''}>${l}</option>`).join('')}</select>`:''}<label>Cerca evento o pronostico</label><input id="query" type="search" value="${U.esc(filter.query)}" placeholder="Squadra, evento, Over…"><small>Il risultato giornaliero usa il riferimento data selezionato.</small>${filter.from&&filter.to&&filter.from>filter.to?'<p class="error">La data iniziale deve precedere quella finale.</p>':''}</div>`}
function limitCard(){const rows=db.bets.filter(b=>U.inRange(b.date,U.bounds('month'))),used=U.round(rows.reduce((n,b)=>n+b.stake,0)),limit=db.settings.monthlyLimit;return limit?`<div class="card"><b>Limite personale mensile</b><p class="${used>limit?'negative':''}">${U.money(used)} di ${U.money(limit)} puntati</p><small>${used>limit?'Limite superato.':'Disponibilità rispetto al limite: '+U.money(Math.max(0,limit-used))} Non blocca l’inserimento.</small></div>`:''}
function render(){document.getElementById('title').textContent={home:'Home',bets:'Scommesse',stats:'Statistiche',accounts:'Altro'}[tab];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const error=document.getElementById('storage-error');error.hidden=!storageError;error.textContent=storageError;document.getElementById('new-bet').disabled=!!storageError;let html='';chartPoints=[];
if(tab==='home'){const pending=db.bets.filter(b=>b.status==='pending');html=`<div class="card hero"><small>SALDO DISPONIBILE</small><div class="big">${U.money(balance())}</div><small>${U.money(pending.reduce((n,b)=>n+b.stake,0))} impegnati · ${pending.length} aperte</small></div>${limitCard()}${kpis(db.bets,{interactive:true,context:'home-kpis'})}<h2 class="section">Scommesse in corso</h2>${pending.map(card).join('')||'<div class="card empty">Nessuna scommessa in corso.<div class="actions" style="justify-content:center"><button data-new>＋ Scommessa</button></div></div>'}`}
if(tab==='bets'){const rows=selectedBets();html=filters()+`<h2 class="section">Storico · ${rows.length}</h2>`+(rows.map(card).join('')||'<div class="card empty">Nessuna scommessa per questi filtri.</div>')}
if(tab==='stats'){const rows=selectedBets(),closed=rows.filter(b=>b.status!=='pending'&&b.settledAt).sort((a,b)=>new Date(a.settledAt)-new Date(b.settledAt));let total=0;chartPoints=closed.map(b=>({date:b.settledAt,value:total=U.round(total+profit(b)),detail:`${U.date(b.settledAt)} · Puntata ${U.money(b.stake)} · Incasso ${U.money(payout(b))} · Profitto ${U.money(profit(b))} · Cumulato ${U.money(total)}`}));html=filters()+kpis(rows,{context:'stats-kpis'})+`<div class="card stats-chart"><h2>Profitto cumulato</h2>${U.chart(chartPoints,'Profitto cumulato in euro')}<small>Ordine di liquidazione. Gli esiti senza data restano nello storico, esclusi dal grafico.</small></div><div class="card"><h2>Singole e multiple</h2><table class="list-table"><tr><th>Tipo</th><th>Numero</th><th>Puntate</th><th>Profitto</th></tr>${[false,true].map(m=>{const r=rows.filter(b=>(b.legs.length>1)===m);return `<tr><td>${m?'Multiple':'Singole'}</td><td>${r.length}</td><td>${U.money(r.reduce((n,b)=>n+b.stake,0))}</td><td>${U.money(r.reduce((n,b)=>n+profit(b),0))}</td></tr>`}).join('')}</table></div><div class="card"><h2>Esiti</h2>${Object.entries(labels).map(([v,l])=>`<div class="row" style="margin:12px 0"><span>${l}</span><b>${rows.filter(b=>b.status===v).length}</b></div>`).join('')}</div>`}
if(tab==='accounts'){html=`<div class="card hero"><small>SALDO DISPONIBILE</small><div class="big">${U.money(balance())}</div><div class="actions"><button data-tx="deposit">Deposita</button><button data-tx="withdraw">Preleva</button><button id="initial">Saldo iniziale</button></div></div><div class="card"><h2>Limite personale</h2><label>Puntate mensili (€), 0 = disattivato</label><input id="monthly-limit" type="number" min="0" step="0.01" value="${db.settings.monthlyLimit}"><button id="save-limit" style="margin-top:10px">Salva limite</button></div>${limitCard()}<div class="card"><h2>Backup e ripristino</h2><p class="muted">Dati salvati solo in questo browser. Ultima esportazione richiesta: ${db.settings.lastExport?U.date(db.settings.lastExport):'mai'}.</p><div class="actions"><button id="export">Esporta JSON</button><button id="import">Importa backup</button></div><input type="file" accept=".json,application/json" id="import-file" hidden></div><h2 class="section">Movimenti</h2>${db.transactions.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(t=>`<div class="card"><div class="row"><b>${t.amount<0?'Prelievo':'Deposito'}</b><span>${U.money(t.amount)}</span></div><p class="muted">${U.date(t.date)}</p><div class="actions"><button data-tx-edit="${t.id}">Modifica</button><button class="danger" data-tx-delete="${t.id}">Elimina</button></div></div>`).join('')||'<div class="card empty">Nessun movimento.</div>'}`}
main.innerHTML=html;bind();U.bindChart(main,chartPoints)}
function undoBet(before,after){U.toast('Esito registrato',()=>{const current=db.bets.find(b=>b.id===before.id);if(JSON.stringify(current)!==JSON.stringify(after)){U.toast('La scommessa è stata modificata: usa Altri esiti scommessa.');return}mutate(n=>n.bets=n.bets.map(b=>b.id===before.id?before:b))})}
function bind(){main.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>betForm());main.querySelectorAll('[data-kpi]').forEach(b=>b.onclick=()=>kpiPanel(b.dataset.kpi,db.bets));main.querySelectorAll('[data-roi]').forEach(b=>b.onclick=e=>{e.stopPropagation();U.modal(U.head('Percentuale vinte')+'<p>Scommesse vinte ÷ (vinte + perse) × 100.</p><p>6 vinte e 4 perse = 60%. Ogni singola o multipla conta come una scommessa, indipendentemente da puntata e quota.</p><p>In corso, annullate e cash out sono escluse dal conteggio. In Statistiche si applicano i filtri selezionati.</p>')});for(const key of ['period','basis','day','from','to','status','query'])document.getElementById(key)?.addEventListener('change',e=>{filter[key]=e.target.value;if(key==='day'&&filter.day)filter.month=filter.day.slice(0,7);render()});main.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{filter.month=U.shiftMonth(filter.month,Number(b.dataset.month));render()});main.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{filter.day=b.dataset.day;render()});main.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>betForm(db.bets.find(x=>x.id===b.dataset.edit)));main.querySelectorAll('[data-settle]').forEach(b=>b.onclick=()=>settleForm(db.bets.find(x=>x.id===b.dataset.settle)));main.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Eliminare la scommessa e ricalcolare il saldo?'))mutate(n=>n.bets=n.bets.filter(x=>x.id!==b.dataset.delete))});main.querySelectorAll('[data-quick]').forEach(btn=>btn.onclick=()=>{const before=U.clone(db.bets.find(b=>b.id===btn.dataset.id));const after={...before,status:btn.dataset.quick,actualPayout:null,settledAt:new Date().toISOString(),legs:before.legs.map(l=>btn.dataset.quick==='won'&&l.status!=='void'?{...l,status:'won'}:l)};if(mutate(n=>n.bets=n.bets.map(b=>b.id===after.id?after:b)))undoBet(before,after)});main.querySelectorAll('[data-tx]').forEach(b=>b.onclick=()=>transactionForm(b.dataset.tx==='withdraw'?-1:1));main.querySelectorAll('[data-tx-edit]').forEach(b=>b.onclick=()=>{const t=db.transactions.find(x=>x.id===b.dataset.txEdit);transactionForm(t.amount<0?-1:1,t)});main.querySelectorAll('[data-tx-delete]').forEach(b=>b.onclick=()=>{if(confirm('Eliminare il movimento e ricalcolare il saldo?'))mutate(n=>n.transactions=n.transactions.filter(t=>t.id!==b.dataset.txDelete))});document.getElementById('save-limit')?.addEventListener('click',()=>{const v=Number(document.getElementById('monthly-limit').value);if(U.finite(v)&&v>=0)mutate(n=>n.settings.monthlyLimit=U.round(v))});document.getElementById('initial')?.addEventListener('click',initialForm);document.getElementById('export')?.addEventListener('click',exportData);document.getElementById('import')?.addEventListener('click',()=>document.getElementById('import-file').click());document.getElementById('import-file')?.addEventListener('change',importData)}
const PICK_GROUPS=[
{id:'over-ft',label:'OVER FT',items:Array.from({length:11},(_,i)=>`Over ${i+.5} FT`)},
{id:'over-ht',label:'OVER HT',items:Array.from({length:11},(_,i)=>`Over ${i+.5} HT`)},
{id:'over-minutes',label:'OVER MINUTI',items:Array.from({length:8},(_,i)=>`Over entro ${(i+1)*10} minuti`)},
{id:'over-asian-ft',label:'OVER ASIATICO FT',items:Array.from({length:5},(_,i)=>`Over ${i+1} Asiatico FT`)},
{id:'over-asian-ht',label:'OVER ASIATICO HT',items:Array.from({length:5},(_,i)=>`Over ${i+1} Asiatico HT`)}
];
function presetButtons(){const favorites=[...new Set(db.settings.favorites)],buttons=rows=>rows.map(p=>`<button type="button" data-pick="${U.esc(p)}">${U.esc(p)}</button>`).join(''),groups=PICK_GROUPS.map(g=>`<button type="button" class="pick-group-button" data-pick-group="${g.id}"><span>${U.esc(g.label)}</span><span aria-hidden="true">›</span></button>`).join('');return `${favorites.length?`<section class="pick-panel-section favorites-section"><div class="pick-panel-section-title"><span aria-hidden="true">★</span> Preferiti</div><div class="pick-panel-buttons">${buttons(favorites)}</div></section>`:''}<section class="pick-panel-section pick-types-section"><div class="pick-panel-section-title">Tipologia esito</div><div class="pick-panel-groups">${groups}</div></section>`}
function groupButtons(group){return `<section class="pick-panel-section pick-values-section"><div class="pick-panel-section-title">${U.esc(group.label)}</div><div class="pick-panel-buttons">${group.items.map(p=>`<button type="button" data-pick="${U.esc(p)}">${U.esc(p)}</button>`).join('')}</div></section>`}
function legHTML(l={},index=0){const pick=U.esc(l.pick||'');return `<details class="leg compact-leg" data-leg-status="${l.status||'pending'}" ${index===0?'open':''}><summary><span class="leg-number">${index+1}</span><span class="leg-summary"><b class="leg-title">${U.esc(l.event||'Nuovo evento')}</b><small class="leg-pick">${U.esc(l.pick||'Partita e pronostico')}</small></span><b class="leg-quote">${l.odds?Number(l.odds).toFixed(2):'—'}</b><span class="leg-chevron">⌄</span></summary><div class="leg-fields"><label>Partita / evento<input class="event" required maxlength="160" placeholder="Es. Inter – Milan" value="${U.esc(l.event||'')}"></label><div class="pick-odds-row"><label>Esito / pronostico<div class="pick-selector"><input class="pick" type="hidden" value="${pick}"><button class="pick-trigger" type="button" aria-haspopup="dialog"><span class="pick-trigger-text">${pick||'Seleziona esito'}</span><span class="pick-trigger-arrow" aria-hidden="true">›</span></button></div></label><label>Quota<input class="odds" type="number" inputmode="decimal" min="1" max="10000" step="any" required placeholder="1.85" value="${l.odds||''}"></label></div><div class="leg-tools"><button class="favorite-toggle" type="button" data-favorite aria-label="Aggiungi pronostico ai preferiti" title="Aggiungi ai preferiti" aria-pressed="false">☆</button><button class="danger" type="button" data-remove-leg aria-label="Rimuovi evento">✕ Rimuovi</button></div></div></details>`}
function betForm(b){const title=b?'Modifica scommessa':'Nuova scommessa',saveLabel=b?'Salva modifiche':'Salva scommessa';const head=`<div class="row editor-head bet-editor-head"><h2>${U.esc(title)}</h2><button class="primary bet-save-icon" type="submit" form="bet-form" aria-label="${U.esc(saveLabel)}" title="${U.esc(saveLabel)}">✓</button></div>`;const d=U.modal(head+`<form id="bet-form"><div class="bet-meta"><label>Puntata (€)<input name="stake" min="0.01" step="0.01" inputmode="decimal" type="number" required placeholder="10,00" value="${b?.stake??'10.00'}"></label><details class="bet-date"><summary><span>Data e ora <span class="date-edit">Modifica</span></span><b id="date-summary"></b></summary><input name="date" aria-label="Data e ora della giocata" type="datetime-local" required value="${U.local(b?new Date(b.date):new Date())}"></details></div><div id="legs">${(b?.legs||[{}]).map(legHTML).join('')}</div><button type="button" id="add-leg">＋ Aggiungi evento alla multipla</button><p id="form-error" class="error" role="alert"></p><div class="bet-savebar"><div id="preview" aria-live="polite"></div></div><div id="pick-panel" class="pick-panel-layer" hidden><button class="pick-panel-scrim" type="button" data-close-pick-panel aria-label="Chiudi pannello esito"></button><section class="pick-panel-card" role="dialog" aria-modal="true" aria-labelledby="pick-panel-title"><div class="pick-panel-head"><small>${b?'MODIFICA SCOMMESSA':'NUOVA SCOMMESSA'}</small><button type="button" id="pick-back" class="pick-back" hidden aria-label="Torna alle tipologie di esito">← Indietro</button><h3 id="pick-panel-title">Scegli tipo di esito</h3><p class="muted" id="pick-panel-help">Scegli una categoria per vedere gli esiti disponibili.</p></div><div class="pick-panel-grid" id="pick-panel-grid"></div><div id="pick-custom-block"><label>Esito personalizzato<input id="pick-custom" maxlength="100" autocomplete="off" placeholder="Es. 1, X2, Goal, Over 2.5 FT"></label><div class="pick-panel-actions"><button type="button" class="primary" id="pick-confirm" aria-label="Conferma esito personalizzato">✓</button></div></div><p class="error" id="pick-panel-error" role="alert"></p></section></div></form>`,{backdropClose:true});const form=d.querySelector('form'),panel=d.querySelector('#pick-panel'),custom=d.querySelector('#pick-custom'),customBlock=d.querySelector('#pick-custom-block'),panelGrid=d.querySelector('#pick-panel-grid'),panelTitle=d.querySelector('#pick-panel-title'),panelHelp=d.querySelector('#pick-panel-help'),back=d.querySelector('#pick-back');let pickTarget=null;
const openLeg=c=>{d.querySelectorAll('.leg').forEach(x=>{x.open=x===c})};
const closePickPanel=()=>{panel.hidden=true;pickTarget=null;d.querySelector('#pick-panel-error').textContent=''};
const choosePick=value=>{if(!pickTarget)return;const v=String(value||'').trim();if(!v)return;pickTarget.querySelector('.pick').value=v;pickTarget.querySelector('.pick-trigger-text').textContent=v;closePickPanel();preview()};
const bindPickPanel=(groupId='')=>{const group=PICK_GROUPS.find(g=>g.id===groupId);if(group){panelTitle.textContent=group.label;panelHelp.textContent='Scegli il valore desiderato.';back.hidden=false;customBlock.hidden=true;panelGrid.innerHTML=groupButtons(group)}else{panelTitle.textContent='Scegli tipo di esito';panelHelp.textContent='Scegli una categoria per vedere gli esiti disponibili.';back.hidden=true;customBlock.hidden=false;panelGrid.innerHTML=presetButtons()}panelGrid.querySelectorAll('[data-pick]').forEach(btn=>btn.onclick=()=>choosePick(btn.dataset.pick));panelGrid.querySelectorAll('[data-pick-group]').forEach(btn=>btn.onclick=()=>bindPickPanel(btn.dataset.pickGroup))};
const openPickPanel=c=>{pickTarget=c;custom.value=c.querySelector('.pick').value;d.querySelector('#pick-panel-error').textContent='';bindPickPanel();panel.hidden=false};
function preview(){const legs=[...d.querySelectorAll('.leg')],q=legs.reduce((n,c)=>n*(c.dataset.legStatus==='void'?1:Number(c.querySelector('.odds').value)),1),valid=legs.every(c=>Number(c.querySelector('.odds').value)>=1)&&Number.isFinite(q);d.querySelector('#preview').innerHTML=`<span>${legs.length===1?'Singola':legs.length+' eventi'} · Quota <b>${valid?q.toFixed(2):'—'}</b></span><span>Incasso <b>${valid?U.money(Number(form.elements.stake.value)*q):'—'}</b></span>`;d.querySelector('#date-summary').textContent=U.validDate(form.elements.date.value)?U.date(form.elements.date.value):'Seleziona data';legs.forEach((c,i)=>{const inp=c.querySelector('.pick');c.querySelector('.leg-number').textContent=i+1;c.querySelector('.leg-title').textContent=c.querySelector('.event').value.trim()||'Nuovo evento';c.querySelector('.leg-pick').textContent=inp.value.trim()||'Partita e pronostico';c.querySelector('.pick-trigger-text').textContent=inp.value.trim()||'Seleziona esito';c.querySelector('.leg-quote').textContent=Number(c.querySelector('.odds').value)>=1?Number(c.querySelector('.odds').value).toFixed(2):'—';c.querySelector('summary').onclick=e=>{e.preventDefault();if(c.open)c.open=false;else openLeg(c)};c.querySelector('.pick-trigger').onclick=()=>openPickPanel(c);const star=c.querySelector('[data-favorite]'),favorite=db.settings.favorites.includes(inp.value.trim());star.textContent=favorite?'★':'☆';star.setAttribute('aria-pressed',String(favorite));star.setAttribute('aria-label',favorite?'Rimuovi pronostico dai preferiti':'Aggiungi pronostico ai preferiti');star.title=favorite?'Rimuovi dai preferiti':'Aggiungi ai preferiti';star.onclick=()=>{const value=inp.value.trim();if(!value){U.toast('Seleziona prima un esito da aggiungere ai preferiti.');return}const wasFavorite=db.settings.favorites.includes(value),n=U.clone(db);n.settings.favorites=wasFavorite?n.settings.favorites.filter(v=>v!==value):[...n.settings.favorites,value];if(commit(n)){U.toast(wasFavorite?'Rimosso dai preferiti':'Aggiunto ai preferiti');if(!panel.hidden)bindPickPanel();preview()}};const remove=c.querySelector('[data-remove-leg]');remove.hidden=legs.length===1;remove.onclick=()=>{const next=c.nextElementSibling||c.previousElementSibling;c.remove();if(next)openLeg(next);preview()}})}
const invalidLeg=()=>[...d.querySelectorAll('.leg')].find(c=>!c.querySelector('.event').value.trim()||!c.querySelector('.pick').value.trim()||!c.querySelector('.odds').checkValidity()||!c.querySelector('.odds').value.trim());
form.addEventListener('invalid',e=>{const c=e.target.closest('.leg');if(c)openLeg(c);else if(e.target.name==='date')d.querySelector('.bet-date').open=true},true);
d.querySelector('[data-close-pick-panel]').onclick=closePickPanel;back.onclick=()=>bindPickPanel();d.querySelector('#pick-confirm').onclick=()=>{const value=custom.value.trim();if(!value)return d.querySelector('#pick-panel-error').textContent='Scrivi un esito oppure scegli una categoria.';choosePick(value)};custom.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();d.querySelector('#pick-confirm').click()}};d.querySelector('.bet-save-icon').onclick=()=>{if(!form.elements.stake.value.trim()){form.elements.stake.value='10.00';preview()}};
d.querySelector('#add-leg').onclick=()=>{const invalid=invalidLeg();if(invalid){openLeg(invalid);d.querySelector('#form-error').textContent='Completa partita, esito e quota prima di aggiungere un altro evento.';const target=!invalid.querySelector('.event').value.trim()?invalid.querySelector('.event'):!invalid.querySelector('.pick').value.trim()?invalid.querySelector('.pick-trigger'):invalid.querySelector('.odds');target.focus();return}const holder=d.querySelector('#legs');holder.insertAdjacentHTML('beforeend',legHTML({},holder.children.length));const added=holder.lastElementChild;openLeg(added);preview();added.querySelector('.event').focus()};form.oninput=e=>{e.target.setCustomValidity?.('');d.querySelector('#form-error').textContent='';preview()};form.onchange=preview;preview();form.onsubmit=e=>{e.preventDefault();if(!form.elements.stake.value.trim())form.elements.stake.value='10.00';if(!panel.hidden)closePickPanel();const invalid=invalidLeg();if(invalid){openLeg(invalid);d.querySelector('#form-error').textContent='Completa partita, esito e quota.';const target=!invalid.querySelector('.event').value.trim()?invalid.querySelector('.event'):!invalid.querySelector('.pick').value.trim()?invalid.querySelector('.pick-trigger'):invalid.querySelector('.odds');target.focus();return}if(!form.checkValidity()){form.reportValidity();return}const f=new FormData(form),legs=[...d.querySelectorAll('.leg')].map(c=>({event:c.querySelector('.event').value.trim(),pick:c.querySelector('.pick').value.trim(),odds:Number(c.querySelector('.odds').value),status:c.dataset.legStatus})),obj={...(b||{id:U.uid(),status:'pending'}),account:db.accounts[0].id,stake:Number(f.get('stake')),date:new Date(f.get('date')).toISOString(),legs};const err=d.querySelector('#form-error');if(legs.some(l=>!l.event||!l.pick)||!Number.isFinite(obj.stake*odds(obj)))return err.textContent='Controlla tutti i campi.';const available=balance()+(b?b.stake-payout(b):0);if(obj.status==='pending'&&obj.stake>available)return err.textContent='Saldo insufficiente. Registra un deposito in Altro.';const n=U.clone(db);n.bets=b?n.bets.map(x=>x.id===b.id?obj:x):[...n.bets,obj];n.settings.recent=[...new Set([...legs.map(l=>l.pick),...n.settings.recent])].slice(0,12);if(commit(n)){d.close();U.toast('Scommessa salvata')}}}
function derivedStatus(legs){if(legs.some(l=>l.status==='lost'))return 'lost';if(legs.every(l=>l.status==='void'))return 'void';if(legs.every(l=>l.status==='won'||l.status==='void'))return 'won';return 'pending'}
function settleForm(b){const d=U.modal(U.head('Altri esiti scommessa')+`<form><h3>Esiti dei singoli eventi</h3>${b.legs.map((l,i)=>`<label>${U.esc(l.event)} · ${U.esc(l.pick)}</label><select data-leg-outcome="${i}">${['pending','won','lost','void'].map(v=>`<option value="${v}" ${l.status===v?'selected':''}>${labels[v]}</option>`).join('')}</select>`).join('')}<label>Esito complessivo</label><select name="status"><option value="auto">Automatico dagli eventi</option>${Object.entries(labels).map(([v,l])=>`<option value="${v}" ${b.status===v?'selected':''}>${l}</option>`).join('')}</select><p id="estimated" class="muted"></p><label>Data e ora dell’esito</label><input name="settled" type="datetime-local" value="${U.local(new Date(b.settledAt||Date.now()))}"><label>Incasso effettivo (€), vuoto = calcolato</label><input name="actual" type="number" min="0" step="0.01" value="${b.actualPayout??(b.status==='cashout'?b.cashout:'')}"><p class="muted">Comprende la puntata restituita. Gli eventi annullati hanno quota effettiva 1, senza perdere la quota originale.</p><p class="error" id="error"></p><div class="save-center"><button class="primary">Salva esito</button></div></form>`);const form=d.querySelector('form');const read=()=>{const legs=b.legs.map((l,i)=>({...l,status:d.querySelector(`[data-leg-outcome="${i}"]`).value}));return {...b,legs,status:form.elements.status.value==='auto'?derivedStatus(legs):form.elements.status.value,actualPayout:null}};const preview=()=>{const n=read();d.querySelector('#estimated').textContent=`${labels[n.status]} · Quota effettiva ${odds(n).toFixed(2)} · Incasso calcolato ${U.money(payout(n))}`;form.elements.actual.disabled=['pending','lost'].includes(n.status);form.elements.settled.disabled=n.status==='pending';form.elements.settled.required=n.status!=='pending';};d.querySelectorAll('[data-leg-outcome]').forEach(el=>el.onchange=()=>{form.elements.status.value='auto';form.elements.actual.value='';preview()});form.elements.status.onchange=preview;preview();form.onsubmit=e=>{e.preventDefault();const n=read(),val=form.elements.actual.value;n.actualPayout=['pending','lost'].includes(n.status)?null:val===''?null:U.round(Number(val));if(n.status==='cashout'&&n.actualPayout==null)return d.querySelector('#error').textContent='Indica l’importo del cash out.';if(n.status==='cashout')n.cashout=n.actualPayout;n.settledAt=n.status==='pending'?null:new Date(form.elements.settled.value).toISOString();if(n.status==='won')n.legs=n.legs.map(l=>l.status==='void'?l:{...l,status:'won'});if(n.status==='void')n.legs=n.legs.map(l=>({...l,status:'void'}));if(n.settledAt&&new Date(n.settledAt)<new Date(n.date))return d.querySelector('#error').textContent='L’esito non può precedere la giocata.';if(mutate(data=>data.bets=data.bets.map(x=>x.id===b.id?n:x))){d.close();undoBet(b,n)}}}
function transactionForm(sign,t){const d=U.modal(U.head(t?'Modifica movimento':sign<0?'Prelievo':'Deposito')+`<form><label>Importo (€)</label><input name="amount" type="number" min="0.01" step="0.01" required value="${t?Math.abs(t.amount):''}"><label>Data e ora</label><input name="date" type="datetime-local" required value="${U.local(t?new Date(t.date):new Date())}"><p class="error" id="error"></p><div class="save-center"><button class="primary">Salva movimento</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),amount=U.round(sign*Number(f.get('amount')));if(sign<0&&balance()-(t?.amount||0)+amount<0)return d.querySelector('#error').textContent='Saldo insufficiente.';const obj={id:t?.id||U.uid(),account:db.accounts[0].id,amount,date:new Date(f.get('date')).toISOString()};if(mutate(n=>n.transactions=t?n.transactions.map(x=>x.id===t.id?obj:x):[...n.transactions,obj]))d.close()}}
function initialForm(){const d=U.modal(U.head('Saldo iniziale')+`<form><label>Saldo prima delle giocate registrate (€)</label><input name="initial" type="number" min="0" step="0.01" required value="${db.accounts[0].initial}"><p class="muted">Per nuovi versamenti usa Deposita.</p><button class="primary">Salva</button></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();if(mutate(n=>n.accounts[0].initial=U.round(Number(new FormData(e.target).get('initial')))))d.close()}}
function exportData(){const n=U.clone(db);n.settings.lastExport=new Date().toISOString();U.download('bet-tracker-backup-'+U.local().slice(0,10)+'.json',n);if(!storageError)commit(n)}
async function importData(e){const file=e.target.files[0];if(!file)return;try{const raw=JSON.parse(await file.text());if(!validDB(raw))throw Error();const n=normalize(raw),d=U.modal(U.head('Ripristina backup')+`<p>${n.bets.length} scommesse · ${n.transactions.length} movimenti</p><p>Il backup sostituirà i dati attuali. Puoi esportarli prima di proseguire.</p><div class="actions"><button id="before-export">Esporta dati attuali</button><button class="primary" id="confirm-import">Ripristina</button></div>`);d.querySelector('#before-export').onclick=exportData;d.querySelector('#confirm-import').onclick=()=>{if(commit(n,{restore:true})){d.close();U.toast('Backup ripristinato')}}}catch(err){U.toast('Backup non valido. Nessun dato modificato.')}finally{e.target.value=''}}
document.getElementById('new-bet').onclick=()=>betForm();

// 1.1.8 — navigazione bidirezionale con transizione coerente con il verso dello swipe.
const TAB_ORDER=['home','bets','stats','accounts'];
let swipeStart=null,tabTransitioning=false;
function prefersReducedMotion(){return !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches}
function setTab(next,{animate=false,direction=0}={}){
  if(!TAB_ORDER.includes(next)||next===tab||tabTransitioning)return;
  const finish=()=>{tab=next;render();window.scrollTo(0,0)};
  if(!animate||!direction||prefersReducedMotion()){finish();return}
  tabTransitioning=true;
  main.classList.remove('tab-exit-left','tab-exit-right','tab-enter-left','tab-enter-right');
  main.classList.add(direction>0?'tab-exit-left':'tab-exit-right');
  setTimeout(()=>{
    finish();
    main.classList.remove('tab-exit-left','tab-exit-right');
    main.classList.add(direction>0?'tab-enter-right':'tab-enter-left');
    setTimeout(()=>{
      main.classList.remove('tab-enter-left','tab-enter-right');
      tabTransitioning=false;
    },210);
  },135);
}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));

function swipeNavigationBlocked(target){
  return !!(target?.closest?.('button,input,select,textarea,a,label,[contenteditable="true"],dialog,.pick-panel-layer,.pick-panel-card,.touch-chart,.pick-grid'));
}
function overlayOpen(){
  return !!document.querySelector('dialog[open],.pick-panel-layer:not([hidden])');
}
main.addEventListener('touchstart',e=>{
  if(tabTransitioning||e.touches.length!==1||overlayOpen()||swipeNavigationBlocked(e.target)){swipeStart=null;return}
  const t=e.touches[0];
  swipeStart={x:t.clientX,y:t.clientY,time:Date.now()};
},{passive:true});
main.addEventListener('touchend',e=>{
  if(!swipeStart||tabTransitioning||e.changedTouches.length!==1){swipeStart=null;return}
  const t=e.changedTouches[0],dx=t.clientX-swipeStart.x,dy=t.clientY-swipeStart.y,elapsed=Date.now()-swipeStart.time;
  swipeStart=null;
  const horizontal=Math.abs(dx)>=70&&Math.abs(dx)>=Math.abs(dy)*1.35&&Math.abs(dy)<=100&&elapsed<=900;
  if(!horizontal||overlayOpen())return;
  const index=TAB_ORDER.indexOf(tab),direction=dx<0?1:-1,next=TAB_ORDER[index+direction];
  if(!next)return;
  setTab(next,{animate:true,direction});
},{passive:true});
main.addEventListener('touchcancel',()=>{swipeStart=null},{passive:true});

document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});render();requestAnimationFrame(()=>{const splash=document.getElementById('splash');if(splash){splash.classList.add('hidden');setTimeout(()=>splash.remove(),350)}});

// Feedback for mouse, touch and keyboard, including dynamically created controls.
document.addEventListener('click',e=>{const button=e.target.closest?.('button');if(!button||button.disabled)return;button.classList.remove('button-tap');void button.offsetWidth;button.classList.add('button-tap');setTimeout(()=>button.classList.remove('button-tap'),240)},true);
